// Manage Product
export const API_MANAGE_PRODUCT_START = 'API_MANAGE_PRODUCT_START'
export const API_MANAGE_PRODUCT_FAILED = 'API_MANAGE_PRODUCT_FAILED'
export const API_MANAGE_PRODUCT_SUCCESS = 'API_MANAGE_PRODUCT_SUCCESS'
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const FETCH_CATEGORY = 'FETCH_CATEGORY'
export const TOGGLE_ADDSUCCESS = 'TOGGLE_ADDSUCCESS'

// Product Package
export const API_PRODUCT_PACKAGE_START = 'API_PRODUCT_PACKAGE_START' 
export const API_PRODUCT_PACKAGE_SUCCESS = 'API_PRODUCT_PACKAGE_SUCCESS' 
export const API_PRODUCT_PACKAGE_FAILED = 'API_PRODUCT_PACKAGE_FAILED' 
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT'
export const ADD_PACKAGE = 'ADD_PACKAGE'
export const EDIT_PACKAGE = 'EDIT_PACKAGE'
export const DELETE_PACKAGE = 'DELETE_PACKAGE'

// Transaction Status
export const API_TRANSACTION_STATUS_START = 'API_TRANSACTION_STATUS_START'
export const API_TRANSACTION_STATUS_SUCCESS = 'API_TRANSACTION_STATUS_SUCCESS'
export const API_TRANSACTION_STATUS_FAILED = 'API_TRANSACTION_STATUS_FAILED'
export const FETCH_PENDING = 'FETCH_PENDING'

// Report
export const API_REPORT_START = 'API_REPORT_START'
export const API_REPORT_SUCCESS = 'API_REPORT_SUCCESS'
export const API_REPORT_FAILED = 'API_REPORT_FAILED'

